server:
  port: 8080
  
logging:
  file: target/app.log
  level:
    ROOT: WARN
    bmw.lbs.demo.controller: TRACE
    
spring:
  cache:
    redis:
      time-to-live: 3600s # set a overdue time for cache

redis:
  host: localhost
  port: 6379
  jedis:
    pool:
      max-active: 5
      max-idle: 10
      max-wait: 10000