server:
  port: 8080
  
logging:
  file: target/app.log
  level:
    ROOT: WARN
    bmw.lbs.demo.controller: TRACE
    
spring:
  cache:
    redis:
      time-to-live: 600s # set a overdue time for cache
    